version: "3"
services:
  tests:
    image: "buildkite/plugin-tester"
    volumes:
      - ".:/plugin:ro"
  lint:
    image: "buildkite/plugin-linter"
    command: ["--id", "envato/cloudformation-output"]
    volumes:
      - ".:/plugin:ro"
