version: "3"
services:
  tests:
    image: "buildkite/plugin-tester"
    volumes:
      - ".:/plugin:ro"
  lint:
    image: "buildkite/plugin-linter"
    command: ["--id", "envato/cloudformation-output"]
    volumes:
      - ".:/plugin:ro"
  shell_check:
    image: koalaman/shellcheck
    command: ["--color=always", "hooks/pre-command"]
    working_dir: /plugin
    volumes:
      - ".:/plugin:ro"
