name: AWS CloudFormation Output
description: Gather AWS Cloudformation output and export them as env vars
author: https://github.com/envato
requirements: []
configuration:
  properties:
    output:
      type: array
  required:
    - output
  additionalProperties: false
