name: CloudformationOptions
description: Gather Cloudformation output and export them as env vars
author: https://github.com/envato
requirements: []
configuration:
  properties:
    outputs:
      type: array
  oneOf:
    required:
      - outputs
  additionalProperties: false
